apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DB_HOST: "mysql"
  DB_NAME: "testdb"
  DB_USER: "testuser"
  config.json: |
    {
      "BASE_URL": "http://localhost:8082"
    }